name: Web Automation Testing

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  # schedule:
    # - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright:v1.52.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20"

      # This step caches the pnpm store directory
      # to speed up installation of dependencies in future runs.
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # - name: Install Playwright
      #   run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm playwright test
        continue-on-error: true
      
      - name: Check report directory
        run: ls -l playwright-report

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
      
      - name: Deploy Test Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
